name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      - main
      - versat_integration
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SHA-pc-emul:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-pc-emul
        run: make test-pc-emul ALGORITHM=SHA256
      - name: test-clean
        run: make test-pc-emul-clean ALGORITHM=SHA256

  SHA-simulation:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: simulate system
        run: make test-sim ALGORITHM=SHA256
      - name: simulation clean
        run: make test-sim-clean ALGORITHM=SHA256

  AES-pc-emul:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-pc-emul
        run: make test-pc-emul ALGORITHM=AES256
      - name: test-clean
        run: make test-pc-emul-clean ALGORITHM=AES256

  AES-simulation:
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: simulate system
        run: make test-sim ALGORITHM=AES256
      - name: simulation clean
        run: make test-sim-clean ALGORITHM=AES256

  AES-fpga:
    runs-on: self-hosted
    timeout-minutes: 75

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: fpga build
        run: make test-fpga ALGORITHM=AES256
      - name: fpga clean
        run: make test-fpga-clean ALGORITHM=AES256

  AES-fusesoc-sim:
    runs-on: self-hosted
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: FuseSoC Simulation
        run: make fusesoc-sim-run ALGORITHM=AES256
      - name: FuseSoC clean
        run: make fusesoc-clean

  AES-fusesoc-fpga:
    runs-on: self-hosted
    timeout-minutes: 75

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: FuseSoC FPGA Test
        run: make fusesoc-fpga-run ALGORITHM=AES256
      - name: FuseSoC clean
        run: make -C fusesoc clean-all
