name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      - main
      - versat_integration
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pc-emul:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-pc-emul
        run: make test-pc-emul
      - name: test-clean
        run: make test-pc-emul-clean

  simulation:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: simulate system
        run: make test-sim
      - name: simulation clean
        run: make test-sim-clean

  fpga:
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: fpga build
        run: make test-fpga
      - name: fpga clean
        run: make test-fpga-clean

  fusesoc-sim:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: FuseSoc Setup
        run: |
          make fusesoc-setup
          source .venv/bin/activate
      - name: FuseSoc Simulation
        run: ./fusesoc.sh sim
      - name: FuseSoc Clean
        run: ./fusesoc.sh clean
      - name: Deactivate Virtual Environment
        run: deactivate
